apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-app.fullname" . }}-config
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.app.env.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.app.env.REDIS_PORT | quote }}
